WorkflowsController#render_task: 334
BatchesController#add_control: 61
Event#update_request: 61
StudiesController#studies_from_scope: 62
ItemsController#asset_lookup_table: 62
Projects::Workflows::ItemsController#print: 62
Batch#create_requests: 64
BatchesController#print_multiplex_barcodes: 65
Studies::AssetGroupsController#print_labels: 65
ReceptionsController#receive_snp_barcode: 66
BatchesController#add_tags: 66
SessionsController#authenticate: 67
StudiesController#create: 68
Request#none: 722
Summary#load_item: 72
ApplicationHelper#completed: 72
ApplicationHelper#tabulated_error_messages_for: 76
Admin::UsersController#remove_user_role: 80
Admin::UsersController#grant_user_role: 80
ReceptionsController#receive_barcode: 81
WorkflowsController#do_cherrypick_task: 82
Admin::InformationsController#update: 85
Admin::ProjectsController#managed_update: 85
AssetsController#lookup: 93
AssetsController#create_plate_layout: 79
ReceptionsController#lookup: 88
BatchesController#start_automatic_qc: 89
Studies::SampleRegistrationController#process_spreadsheet: 92
Studies::SampleRegistrationController#create: 98
PicoSet#calculate_slope_and_intercept: 100
Event#update_properties: 104
BatchesController#print_barcodes: 104
Admin::StudiesController#filter: 107
Admin::ProjectsController#filter: 107
Batch#generate_tecan_data: 108
PicoSetsController#create: 108
SamplesController#accession: 111
Batch#swap: 120
StudiesController#accession: 121
SamplesController#is_check_params_move: 122
BatchesController#create: 123
RequestsController#create: 129
SamplesController#move: 131
Studies::WorkflowsController#show_summary: 131
AssetsController#create_request: 134
RequestsController#index: 138
Studies::Workflows::SubmissionsController#create: 136
PicoSet#generate_results_of_each_well: 151
CherrypickTask#map_wells_to_plates: 172
SampleRegistrar#create: 201
BatchesController#fail_items: 129
Tasks::AssignTagsHandler#do_assign_tags_task: 68
Tasks::CherrypickHandler#render_cherrypick_task: 77
Tasks::CherrypickHandler#do_cherrypick_task: 77
