<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict --tags ~@wip --tags ~@deprecated --color"
%>
default: <%= std_opts %> features
wip: --tags @wip:3 --wip features
nojs:  "--format progress --strict --tags ~@wip --tags ~@deprecated --tags ~@javascript --color -r features"
jsonly:  "--format pretty --strict --tags @javascript --tags ~@wip --tags ~@deprecated --color -r features"
deprecated: --tags @deprecated:3 --deprecated features
rerun: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip
