name: Build and publish Docker image
on:
  push:
    branches:
      - testing-docker

env:
  IMAGE_NAME: ${{ github.repository }}/${{ github.event.repository.name }}

jobs:
  build_and_publish:
    runs-on: ubuntu-18.04

    steps:
    - run: env

    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: /var/lib/docker
        key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-
    - name: Build and tag the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/}
    - name: Tag (latest) the Docker image
      run: docker tag docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/} docker.pkg.github.com/${IMAGE_NAME}:latest
      if: github.ref == 'refs/heads/master'

    - name: Login to registry
      run: docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
    - name: Publish image
      run: docker push docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/}
    - name: Publish image (latest)
      run: docker push docker.pkg.github.com/${IMAGE_NAME}:latest
      if: github.ref == 'refs/heads/master'
